export const useDataTable = () => ({
  filterValue: "",
  setFilterValue: () => {},
  data: [],
  isLoading: false,
  tableContainerRef: { current: null },
  setData: () => {},
  filter: "",
  setFilter: () => {},
  selectedIds: [],
  setSelectedIds: () => {},
  page: 1,
  setPage: () => {},
  pageSize: 10,
  setPageSize: () => {},
  sortBy: "",
  setSortBy: () => {},
  sortDirection: "asc",
  setSortDirection: () => {},
  columns: [],
  setColumns: () => {},
  selectedRows: [],
  setSelectedRows: () => {},
  totalRecords: 0,
});